### ISSUE TITLE
UIWebView+TS_JavaScriptContext审核会被拒，提醒下提交商店的开发者

### ISSUE THREAD

**Issue by WuChaoDong** [GitWangKai/WKJavaScriptBridge#3]
看了文章简介分析的很全面，粗略看了下插件的写法，跟ionic的插件开发很像，给大佬点赞👍

**Comment by GitWangKai** [comment]
这也是我最担心的问题，现在UIWebView+TS_JavaScriptContext在项目里是一定会被拒吗

**Comment by WuChaoDong** [comment]
是的，之前用到这个被拒绝了，说调用了私有API，原项目的issues里面也提到了被拒的现象，查找网上的解决方案，找到一个替代方案，目前线上项目在用，效果不是很理想，代码如下：
- (void) webView: (id) unused didCreateJavaScriptContext: (JSContext*) ctx forFrame: (id<TSWebFrame>) frame
{
    if (!ctx)
        return;
    [[NSNotificationCenter defaultCenter] postNotificationName:@"LLCreatJSContex" object:ctx];
}
替换为通知，暂时满足需求，还没有找到更好的替代方案

**Comment by GitWangKai** [comment]
调研了一下，UIWebView现在大公司项目基本上都被砍掉了替换成了WKWebView。我又额外加了个URL拦截的方式通信解决UIWebView可能被拒问题，感觉只能这样了。
