### ISSUE TITLE
构建小程序的方案和思路

### ISSUE THREAD

**Issue by iDivines** [GitWangKai/WKJavaScriptBridge#4]
我看见您后续有构建小程序的计划，能说下思路吗，我也想参与下。

**Comment by GitWangKai** [comment]
欢迎啊👏，但是小程序这个，具体实施的话将是一个比较庞大的知识体系，涉及到前端、安卓、iOS，目前IDE的选择还没有想。底层渲染打算采用webView,Native,flutter三条管道，最后将JS代码构建一个统一的AST目标代码层，适配三种方案。通过对构建的AST树进行分析审核，安全把控。还要有一个发布平台，用来对离线包、小程序进行发布审核。大概思路是这样。

**Comment by iDivines** [comment]
@GitWangKai  给您发了封邮件
